### ISSUE TITLE
Loading Subtraction Module Issue

### ISSUE THREAD

**Issue by jmdc112596** [quatrope/ProperImage#71]
Hi! I downloaded ProperImage via pip, and it was successful. I can import **properimage** and **properimage.single_image** just fine, but when I try to import **subtract** from **properimage.operations**, it says the **properimage.operations** module doesn't exist. Any idea why this would happen? Thanks for your help! - John

**Comment by BrunoSanchez** [comment]
Hi!
This sounds like the pip release is not exactly identical to the github most recent master branch.
I suppose that this might have happened because we need to update our CI service, probably by setting up github actions or similar.

Will get to this issue in the next days (hopefully sooner)

**Comment by martinberoiz** [comment]
can you print `proper image.__version__`? It would be good to know if any specific version has problems.

**Comment by jmdc112596** [comment]
It says I'm running on version 0.7

**Comment by BrunoSanchez** [comment]
I have found that that version is the latest available in pypi. Aparently, this was an unstable release, and we never noticed it. I am publishing a new release tonight. 
After that I will let you know, so you can try re-installing and running the code.

**Comment by BrunoSanchez** [comment]
@jmdc112596 Please try to run the installation from pip, you would probably need to use the `-U` flag (or `--upgrade`). Check that version is 0.7.1

**Comment by jmdc112596** [comment]
It imported! Thanks so much for the fix! I'll let you know if I find anything else or have any more issues. Thanks again! - John

**Comment by BrunoSanchez** [comment]
Issue was resolved by fixing an unstable release.
