### ISSUE TITLE
propersubtract

### ISSUE THREAD

**Issue by chornelis-08** [quatrope/ProperImage#72]
hello sir, thanks for your code. But, iam sorry, when i use this code
>>> from properimage import propersubtract as ps
>>> D, P, Scorr, mask = ps.subtract(ref=ref_path, new=new_path, smooth_psf=False, fitted_psf=True,
...                             align=False, iterative=False, beta=False, shift=False)

error said like this
"AttributeError: module 'properimage.propersubtract' has no attribute 'subtract'"
can you help me sir?

**Comment by BrunoSanchez** [comment]
How are you doing?
Thanks for this issue, I just realized that the readme contains outdated API code. Please refer to the documentation at https://properimage.readthedocs.io/ for a complete and up-to-date description of the package. 
Again I am sorry for the time lost, I will see that it's updated asap.

**Comment by chornelis-08** [comment]
thanks sir for your comment, actually now i am studying your code to finish my thesis. 
i hope, you can help me, if i have a problem again :)

my regards, 
chornelis
